### ISSUE TITLE
Thanks for sharing, can you support xcode15.x

### ISSUE THREAD

**Issue by LiuSky** [codetronik/ollvm-xcode#2]

**Comment by codetronik** [comment]
I'm watching Apple completely discard the legacy pass.
I think I'll probably start developing it after July.

**Comment by LiuSky** [comment]
I found out from another project of yours that you can support xcode15? https://github.com/codetronik/CodeLabyrinth

**Comment by codetronik** [comment]
The repo is currently only supporting clang, and I plan to support the swift in the future.

**Comment by LiuSky** [comment]
cool
